export const landingHtml = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Guardrail Wallet is an open-source payment firewall for AI agents. Enforce spending policies, require human approval, and integrate through one narrow API.">
<meta name="robots" content="index,follow,max-image-preview:large">
<meta name="theme-color" content="#f3efdf">
<link rel="canonical" href="https://patronhill.ru/">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Guardrail Wallet">
<meta property="og:title" content="Guardrail Wallet | Payment firewall for AI agents">
<meta property="og:description" content="Give AI agents a payment request API, not direct access to funds. Policies decide: allow, deny, or require human approval.">
<meta property="og:url" content="https://patronhill.ru/">
<meta name="twitter:card" content="summary">
<title>Guardrail Wallet | Payment firewall for AI agents</title>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"SoftwareApplication","name":"Guardrail Wallet","applicationCategory":"FinanceApplication","operatingSystem":"Linux, Docker","url":"https://patronhill.ru/","downloadUrl":"https://github.com/nordpaul/guardrail-wallet","softwareVersion":"0.1.0","license":"https://opensource.org/licenses/MIT","description":"Open-source payment firewall for AI agents with deterministic spending policies and human approval.","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"codeRepository":"https://github.com/nordpaul/guardrail-wallet"}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Syne:wght@500;600;700;800&display=swap" rel="stylesheet">
<style>
:root{--ink:#172019;--paper:#f3efdf;--acid:#c9ff45;--ember:#f0643b;--white:#fffdf5}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:"DM Mono",monospace;overflow-x:hidden}
body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.26;background-image:linear-gradient(var(--ink) 1px,transparent 1px),linear-gradient(90deg,var(--ink) 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(#000,transparent 75%)}
a{color:inherit}.shell{width:min(1180px,calc(100% - 34px));margin:auto;position:relative}.nav{height:84px;display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid var(--ink)}
.nav a{text-decoration:none;margin-left:24px;font-size:11px;text-transform:uppercase}.mark{font:800 18px Syne,sans-serif}.mark i{display:inline-block;width:13px;height:13px;background:var(--acid);border:2px solid var(--ink);margin-right:8px;transform:rotate(45deg)}
.hero{min-height:690px;display:grid;grid-template-columns:1.35fr .65fr;gap:44px;align-items:center;padding:78px 0}.eyebrow{display:inline-flex;gap:9px;align-items:center;border:2px solid var(--ink);background:var(--white);padding:8px 11px;font-size:10px;text-transform:uppercase;box-shadow:4px 4px 0 var(--ink)}.eyebrow b{width:8px;height:8px;background:var(--acid);border-radius:50%}
h1,h2,h3{font-family:Syne,sans-serif;margin:0;letter-spacing:-.055em}h1{font-size:clamp(58px,8.8vw,126px);line-height:.82;margin:34px 0}.strike{display:block;color:var(--ember);transform:translateX(6vw)}.lede{max-width:650px;font-size:16px;line-height:1.75}.actions{display:flex;gap:12px;margin-top:34px;flex-wrap:wrap}.button{display:inline-block;padding:15px 19px;border:2px solid var(--ink);background:var(--ink);color:var(--white);text-decoration:none;font:700 14px Syne,sans-serif;box-shadow:5px 5px 0 var(--ember);transition:.18s}.button:hover{transform:translate(3px,3px);box-shadow:2px 2px 0 var(--ember)}.button.alt{background:var(--acid);color:var(--ink);box-shadow:5px 5px 0 var(--ink)}
.dial{aspect-ratio:1;border:2px solid var(--ink);border-radius:50%;background:var(--white);display:grid;place-items:center;position:relative;animation:float 5s ease-in-out infinite}.dial:before,.dial:after{content:"";position:absolute;border:2px solid var(--ink);border-radius:50%}.dial:before{inset:13%}.dial:after{inset:29%;background:var(--acid)}.needle{height:46%;width:4px;background:var(--ember);transform-origin:bottom;transform:translateY(-50%) rotate(38deg);z-index:2}.dial-label{position:absolute;bottom:18%;z-index:3;font:700 12px Syne,sans-serif;text-transform:uppercase}
.band{background:var(--ink);color:var(--white);padding:19px 0;overflow:hidden}.ticker{white-space:nowrap;font:700 18px Syne,sans-serif;word-spacing:20px;animation:marquee 22s linear infinite}.ticker span{color:var(--acid)}
.section{padding:105px 0;border-bottom:2px solid var(--ink)}.section-head{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-bottom:54px}.section h2{font-size:clamp(40px,6vw,82px);line-height:.92}.section-copy{font-size:13px;line-height:1.8;max-width:550px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{border:2px solid var(--ink);background:var(--white);padding:27px;min-height:220px}.card:nth-child(2){background:var(--acid)}.card:nth-child(3){background:var(--ember);color:var(--white)}.num{font:700 11px Syne,sans-serif}.card h3{font-size:28px;margin:50px 0 13px}.card p{font-size:12px;line-height:1.7;margin:0}
.demo{display:grid;grid-template-columns:.8fr 1.2fr;gap:20px}.terminal{background:#111813;color:#d9e4d9;border:2px solid var(--ink);padding:24px;box-shadow:9px 9px 0 var(--ember);overflow:auto}.terminal .bar{color:var(--acid);margin-bottom:18px}.terminal pre{font:11px/1.75 "DM Mono",monospace;white-space:pre-wrap;margin:0}.demo-note{border:2px solid var(--ink);padding:28px;background:var(--acid)}.demo-note code{background:var(--ink);color:var(--white);padding:4px 7px}.demo-note h3{font-size:35px;margin-bottom:22px}.demo-note p{font-size:12px;line-height:1.8}
.support{background:var(--ember);color:var(--white)}.support .button{background:var(--acid);color:var(--ink);box-shadow:6px 6px 0 var(--white)}.wallet{display:block;margin:25px 0;font-size:11px;overflow-wrap:anywhere}.footer{padding:30px 0;display:flex;justify-content:space-between;font-size:10px}
.hero-copy>*{animation:reveal .7s both}.hero-copy>*:nth-child(2){animation-delay:.08s}.hero-copy>*:nth-child(3){animation-delay:.16s}.hero-copy>*:nth-child(4){animation-delay:.24s}@keyframes reveal{from{opacity:0;transform:translateY(22px)}to{opacity:1;transform:none}}@keyframes float{50%{transform:translateY(-12px) rotate(-2deg)}}@keyframes marquee{to{transform:translateX(-50%)}}
@media(max-width:780px){.nav nav{display:none}.hero{grid-template-columns:1fr;min-height:auto;padding:65px 0 90px}.dial{width:68%;margin:20px auto 0}.strike{transform:none}.section{padding:75px 0}.section-head,.demo{grid-template-columns:1fr}.grid3{grid-template-columns:1fr}.card{min-height:180px}.footer{gap:20px;flex-direction:column}.ticker{font-size:14px}}
</style></head>
<body><div class="shell"><header class="nav"><a class="mark" href="/"><i></i>GUARDRAIL WALLET</a><nav><a href="#how">How it works</a><a href="/docs">Docs</a><a href="/api">API</a><a href="/dashboard">Demo</a><a href="#support">Support</a></nav></header>
<main class="hero"><div class="hero-copy"><div class="eyebrow"><b></b> Open-source AI agent payments</div><h1>PAYMENT <span class="strike">FIREWALL.</span></h1><p class="lede">Give AI agents a narrow payment request API, not direct access to funds. Guardrail Wallet evaluates every request against deterministic spending policies: allow, deny, or require human approval.</p><div class="actions"><a class="button" href="/dashboard">Try the live sandbox</a><a class="button alt" href="/docs">Read the documentation</a></div></div><div class="dial"><div class="needle"></div><div class="dial-label">risk / bounded</div></div></main></div>
<div class="band"><div class="ticker">REQUEST <span>NOT</span> SPEND &nbsp; POLICY <span>BEFORE</span> PAYMENT &nbsp; HUMAN <span>WHEN</span> NEEDED &nbsp; REQUEST <span>NOT</span> SPEND &nbsp; POLICY <span>BEFORE</span> PAYMENT &nbsp; HUMAN <span>WHEN</span> NEEDED</div></div>
<section class="section" id="how"><div class="shell"><div class="section-head"><h2>THREE GATES.<br>ONE API.</h2><p class="section-copy">The agent knows one credential: the request key. It cannot access owner controls or settlement secrets. Every request moves through deterministic rules before any executor sees it.</p></div><div class="grid3"><article class="card"><span class="num">01 / REQUEST</span><h3>Agent asks</h3><p>A narrow idempotent API accepts recipient, amount, category and memo. Retries never duplicate a payment.</p></article><article class="card"><span class="num">02 / DECIDE</span><h3>Policy judges</h3><p>Limits, velocity, categories and recipient history produce an explainable decision.</p></article><article class="card"><span class="num">03 / CONTROL</span><h3>Human signs off</h3><p>Unusual requests wait in Telegram or the dashboard. Timeouts fail closed.</p></article></div></div></section>
<section class="section" id="demo"><div class="shell"><div class="section-head"><h2>A SANDBOX<br>FOR AGENTS.</h2><p class="section-copy">The hosted demo uses a fake executor. Integrate the complete request, policy, approval and polling lifecycle without exposing a wallet, mnemonic or real balance. <a href="/docs">Learn how the demo works.</a></p></div><div class="demo"><aside class="demo-note"><h3>Shared demo</h3><p>Agent key<br><code>guardrail-demo-agent</code></p><p>Dashboard key<br><code>guardrail-demo-owner</code></p><p>Sandbox only: no real payment is broadcast. Records are public and may be reset. Never submit secrets or personal data.</p><a class="button" href="/dashboard">Inspect requests</a></aside><div class="terminal"><div class="bar">guardrail@demo:~$ request-payment</div><pre>POST /v1/payments/request
Authorization: Bearer guardrail-demo-agent

{
  "idempotency_key": "demo-unique-001",
  "recipient": {"address": "EQDemoMerchant"},
  "amount": {"value": 8.50, "currency": "USD"},
  "category": "groceries"
}</pre></div></div></div></section>
<section class="section support" id="support"><div class="shell"><div class="section-head"><h2>FUND THE<br>GUARDRAIL.</h2><div><p class="section-copy">Guardrail Wallet is MIT-licensed. Support funds security research, the on-chain extension, agent SDKs and public infrastructure.</p><code class="wallet">UQCLbq0UGD65ljHQGlqF5pNgMAWDgE_bnavRxSSRZy-V3rEJ</code><a class="button" href="https://app.tonkeeper.com/transfer/UQCLbq0UGD65ljHQGlqF5pNgMAWDgE_bnavRxSSRZy-V3rEJ?text=Support%20Guardrail%20Wallet">Support with TON</a></div></div></div></section>
<footer class="shell footer"><span>Guardrail Wallet / MIT / 2026</span><span><a href="/docs">Documentation</a> · <a href="/docs/ru">Русский</a> · <a href="/api">API</a> · Request is not permission.</span></footer></body></html>`;
